image: node:8-jessie

before_script:
  - apt-get install --no-install-recommends -y libopenjp2-tools
  - cd desktop-app

stages:
  - buildPublish

build_and_publish:
  stage: buildPublish
  script:
    - yarn
    - yarn run package-ci

