MONGO_USERNAME: responsively-test
MONGO_PASSWORD: abMPVW652j2ImC99
MONGO_HOSTNAME: responsively-2oqf0.mongodb.net
MONGO_PORT: 27017
MONGO_DB: app-dev
SENDGRID_API_KEY: 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
SEND_MAIL: true
RAZOR_PAY_API_KEY: rzp_test_DVeigAo0o0my9U
RAZOR_API_SECRET_KEY: SGNOlY6m4q7u10ZSs9bJSeND
RAZOR_PAY_WEBHOOK_SECRET: ye9NgW6f8cth29N3MxVNcekJw97AeD
WEBSITE_URL: https://dev.responsively.app