MONGO_USERNAME: responsively-test
MONGO_PASSWORD: abMPVW652j2ImC99
MONGO_HOSTNAME: responsively-2oqf0.mongodb.net
MONGO_PORT: 27017
MONGO_DB: app-prod
SENDGRID_API_KEY: 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
SEND_MAIL: true
RAZOR_PAY_API_KEY: rzp_live_MfwqMz9wLy7gQp
RAZOR_API_SECRET_KEY: LdMDhLcJsr7cCcC1USezZ3hj
RAZOR_PAY_WEBHOOK_SECRET: fk5rVJejW774NgMcm7FRsNdc6yUZqY
WEBSITE_URL: https://responsively.app